# IANNWTF - Homework 07
(by Group 17 - Nils Niehaus, Philipp Bauer, Marlon Dammann)

In [52]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds
from tqdm import tqdm

## 1 - Generating the dataset

In [264]:
def integration_task(seq_len, num_samples):
    for _ in range(num_samples):
        data = np.random.normal(size=seq_len)
        target = True if np.sum(data) > 0 else False
        data = np.expand_dims(data,-1)
        yield data, target

In [265]:
def my_integration_task():
    for elem in integration_task(10, 50000):
        yield elem

In [266]:
dataset = tf.data.Dataset.from_generator(
    my_integration_task,
    output_signature=(
        tf.TensorSpec(shape=(10,1),dtype='float32'),
        tf.TensorSpec(shape=(),dtype='float32')
    )
)

In [267]:
for elem in dataset.take(1):
    print(elem)

(<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 1.1889379 ],
       [-1.2033726 ],
       [ 1.0986694 ],
       [-0.14544404],
       [ 0.17247747],
       [ 1.275339  ],
       [ 0.72373897],
       [ 0.59806794],
       [ 0.6303027 ],
       [-0.34983912]], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)


## 2 - Model

In [260]:
class LSTM_Cell(tf.keras.layers.Layer):
    def __init__(self, units):
        super(LSTM_Cell, self).__init__()
        self.units = units
    
    def build(self, input_shape):
        self.forget_gate = tf.keras.layers.Dense()
        self.input_gate = tf.keras.layers.Dense()
        self.output_gate = tf.keras.layers.Dense()
        
        
        
        
#         self.w = self.add_weight(shape=(input_shape[-1], self.units),
#                                initializer='random_normal',
#                                trainable=True)
#         self.b = self.add_weight(shape=(self.units,),
#                                initializer='random_normal',
#                                trainable=True)
    
    def call(self, x, states):
        cell_state = states[0]
        hidden = states[1]
        x = tf.concat([x, states[1]])
        cell_state = tf.matmul(self.forget_gate(x), cell_state)
        cell_state_candidate = tf.matmul(self.input_gate(x), self.tanh_layer_blabla(x))
        cell_state = cell_state_candidate + cell_state
        x = self.output_gate(x)
        hidden = tf.matmul(x,tf.keras.nn.tanh(cell_state))
        return hidden, cell_state

In [262]:
class LSTM_Layer:
    def __init__(self):
        self.units = [LSTM_Cell(xy) for _ in range(xy)]
    def call(self, x):
        pass

In [261]:
class LSTM_Model:
    def __init__(self):
        pass
    def call(self, x):
        pass

## 3 - Training